### ISSUE TITLE
Installation with Linuxbrew fails

### ISSUE THREAD

**Issue by m-burg** [lfe/lfe#355] opened 2018-05-27 06:34 UTC
Here is the log output from `brew install lfe`
```
==> Downloading https://github.com/rvirding/lfe/archive/v1.3.tar.gz
Already downloaded: /home/michel/.cache/Homebrew/lfe-1.3.tar.gz
==> make
Last 15 lines from /home/michel/.cache/Homebrew/Logs/lfe/01.make:
erlc -I include -o ebin -DERLANG_VERSION=\"20.3.6\" -DHAS_MAPS=true -DHAS_FULL_KEYS=true -DNEW_REC_CORE=true -DNEW_RAND=true -W1 src/lfe_types.erl
erlc -I include -o ebin -DERLANG_VERSION=\"20.3.6\" -DHAS_MAPS=true -DHAS_FULL_KEYS=true -DNEW_REC_CORE=true -DNEW_RAND=true -W1 src/lfe_init.erl
erlc -I include -o ebin -DERLANG_VERSION=\"20.3.6\" -DHAS_MAPS=true -DHAS_FULL_KEYS=true -DNEW_REC_CORE=true -DNEW_RAND=true -W1 src/lfe_eval.erl
erlc -I include -o ebin -DERLANG_VERSION=\"20.3.6\" -DHAS_MAPS=true -DHAS_FULL_KEYS=true -DNEW_REC_CORE=true -DNEW_RAND=true -W1 src/lfe.erl
erlc -o src src/lfe_scan.xrl
install -m755 bin/lfeexec /usr/local/lib/lfe/bin
install: cannot stat 'bin/lfeexec': No such file or directory
Makefile:121: recipe for target 'bin/lfeexec' failed
make[1]: *** [bin/lfeexec] Error 1
make[1]: *** Waiting for unfinished jobs....
src/lfe_types.erl:37: Warning: export_all flag enabled - all functions will be exported
rm src/lfe_scan.erl
make[1]: Leaving directory '/tmp/lfe-20180527-7047-e845ta/lfe-1.3'
Makefile:95: recipe for target 'compile' failed
make: *** [compile] Error 2
```

I am usisg Ubuntu 16.04

**Comment by oubiwann** [comment] 2018-05-31 13:10
Hrm, good to know. We have only tested brew on Mac.

**Comment by oubiwann** [comment] 2018-05-31 13:11
I suspect, though, that this is a duplicate of issue #342.

**Comment by oubiwann** [comment] 2018-05-31 13:13
The fix is in the `develop` branch, and once that's merged to master + released, and once Homebrew gets updated with the latest, this issue should go away.

**Comment by rvirding** [comment] 2018-06-03 21:53
Yes, the problem with this is that I have a mac and there everything just works fine. A simple way around it in the master branch is to by hand first do:

    cc -o bin/lfeexec c_src/lfeexec.c

then it works. I don't why there is this problem.

**Comment by oubiwann** [comment] 2020-10-14 16:47
LFE 2.0 is on the way ... when that's released, the Brew maintainers will be able to consume it.

Going to close this ticket, as the code-fix has been in place for a while.

**Closed as completed by oubiwann** 2020-10-14 16:47 UTC
Labels: bug, duplicate, status:merged
