### ISSUE TITLE
Installation fails on debian

### ISSUE THREAD

**Issue by MaximilianAlgehed** [lfe/lfe#326] opened 2017-03-25 15:37 UTC
Hello,

I am trying to `sudo make install` and I get the following error:
```
install -m644 doc/man/*.3 /usr/local/share/man/man3/
install: target '/usr/local/share/man/man3/' is not a directory: No such file or directory
```
Running `ls -lah /usr/local/share/man/` yields:
```
drwxrwsr-x  4 root staff 4.0K Mar 25 16:22 .
drwxrwsr-x 12 root staff 4.0K Jan  2 00:47 ..
drwxr-sr-x  2 root staff 4.0K Mar 25 16:34 man1
drwxr-sr-x  2 root staff 4.0K Mar 25 16:13 man{1,3,7}
```
If I replace the `install-man` entry in the makefile
with a dummy entry like `echo "hello"` I instead get
the following error message
```
install -m755 bin/lfe{,c,doc,script} /usr/local/lib/lfe/bin
install: cannot stat 'bin/lfe{,c,doc,script}': No such file or directory
Makefile:118: recipe for target 'install' failed
make: *** [install] Error 1
```

Any clues as to what I'm doing wrong? Help greatly appreciated.

**Comment by yurrriq** [comment] 2017-03-26 01:43
Hmm, I'll take a look. I think I'm responsible for that code. Thanks for the report.

**Comment by yurrriq** [comment] 2017-03-26 01:47
Can you give me some more information about your setup? Which versions of Debian, Erlang, rebar3 (if any), pandoc (if any) and LFE are you using?

**Comment by MaximilianAlgehed** [comment] 2017-03-26 06:13
Debian version:
```
$ cat /etc/issue
Debian GNU/Linux stretch/sid \n \l

$ cat /etc/debian_version 
stretch/sid
```
Erlang version:
```
re$ erl
Erlang/OTP 19 [erts-8.2] [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]

Eshell V8.2  (abort with ^G)
```
rebar3:
```
$ rebar3 --version
rebar 3.3.6 on Erlang/OTP 19 Erts 8.2
```
pandoc:
```
$ pandoc --version
pandoc 1.17.2
```
LFE version is the current HEAD of `develop`.

I did not realise I was on `develop` until just now (I was assuming `master` was the default branch...).
When I:
```
$ git checkout master
$ make clean
$ make install
```
It works just fine, which is good.
The `make clean` is necessary as the binaries that are in `bin` by default crash on startup on my system.

I apologise for wasting your time on my silly error, but I hope the informatioń I have provided can be of some use anyway.

**Comment by yurrriq** [comment] 2017-03-26 06:29
This is definitely not a waste of time. `develop` is where all the latest code goes, which is occasionally broken by new features. Tagged versions are generally a safe bet (otherwise please let us know right away).

The scripts in `bin/` expect LFE to be built with or without `rebar3`, i.e. the compiled `.beam` files should be in `ebin/` or `_build/default/lib/lfe/ebin/`. I don't think `make clean` is necessary, but it can't hurt.

I'm glad this is working for you now, but I'm still curious to figure out what broke before.

**Comment by rvirding** [comment] 2017-04-04 21:56
Is there any difference in Makefile that could cause this?

**Comment by rvirding** [comment] 2017-05-15 13:54
Does anyone know if this is still a problem with the `develop` branch? I would like to merge`develop` into `master` and make a new release, which I can't do if this problem still remains.

**Comment by oubiwann** [comment] 2017-05-16 13:56
I have tested on jessie (just confirmed again). The issue was filed against sid, so I'll test on that too.

**Comment by oubiwann** [comment] 2017-05-16 14:32
tested on sid, build works fine, man pages install is definitely broken. It's also broken on jesse (I only tested `make` in my previous comment; not `make install`). 

The reason for this is that on new systems, the `man1`, `man3`, and `man7` directories haven't been created. We need to do a few things:

1. Ensure that `man` is in the user's `$PATH`; if not, then skip the man page installation
1. If `man` is available, we run the man install target, but create `man1`, `man3`, and `man7` dirs first
1. Run `mandb` after installation so all the man bits are properly updated

Since we're not installing LFE and man pages with a package manager, `local` is the way to go (i.e., `/usr/local/share/man`).

I've created a ticket to ensure that LFE docker images for all platforms run `make install` so that we are exercising that bit of the install process:
 * https://github.com/lfex/dockerfiles/issues/22

**Comment by oubiwann** [comment] 2017-05-19 17:54
I've got a branch where I'm working on a fix for this now ...

**Comment by oubiwann** [comment] 2017-05-19 20:49
FYI, the root cause of this is that on Debian gnumake uses the old Bourne shell which doesn't do curly expansion.

**Comment by oubiwann** [comment] 2017-05-19 21:12
There's also another part of the install that uses curly expansion, and once I got past the docs install, found that the bin install on Debian for LFE also failed. This is fixed in the branch.

PR on its way shortly ...

**Comment by yurrriq** [comment] 2017-05-19 23:01
@oubiwann, thanks for the GNU Make tip. I'm used to developing for 4.x, which probably contributed to my breaking this, if it was indeed me :smile:. It's helpful knowledge in general anyway.

**Closed as completed** 2017-05-23 16:12 UTC
