### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by dryjins** [lfe/lfe#189] opened 2016-03-03 07:05 UTC
I am following "LFE Quick Start" using my VM Ubuntu 14.04  hosted by Window 10 but can't compile LFE from the source. Please see this log.
## I use Erlang(R16B03)

if which rebar.cmd > /dev/null; \
    then ERL_LIBS=.:$ERL_LIBS rebar.cmd compile; \
    elif which rebar > /dev/null; \
    then ERL_LIBS=.:$ERL_LIBS rebar compile; \
    else \
    make  erlc-lfec; \
    fi
==> lfe (compile)
ecp: #(cl ())
src/cl.lfe:522: illegal guard
make: **\* [compile] Error 1

---

**Comment by yurrriq** [comment] 2016-03-03 07:32
@Dry-Jins, see #182 for more discussion.

@rvirding, @oubiwann, et al., is there a quick and dirty patch we can apply to quell the flood of issues?

**Comment by oubiwann** [comment] 2016-03-03 14:13
@Dry-Jins There's a lot of discussion in that ticket -- here's what you can do immediately:
- Open up the `Makefile` in the clone you made of the lfe repo
-  Change this target:

``` Makefile
compile: maps_opts.mk
    if which rebar.cmd > /dev/null; \
    then ERL_LIBS=.:$$ERL_LIBS rebar.cmd compile; \
    elif which rebar > /dev/null; \
    then ERL_LIBS=.:$$ERL_LIBS rebar compile; \
    else \
    $(MAKE) $(MFLAGS) erlc-lfec; \
    fi
```

To this:

``` Makefile
compile: maps_opts.mk
    $(MAKE) $(MFLAGS) erlc-lfec;
```
- Ensure the whitespace before `$(MAKE)` is a tab
- Re-run the `make` command from your shell

That _should_ do it.

@rvirding:
- I don't think that the `rebar` code actually look for `lfec` -- it looks like the plugin is doing a `whereis` for the `lfe_comp` module.
- Which means that the problem is likely due to the `cl.lfe` file being put "in line" for compile by rebar before the `lfe_comp.erl` file
- I will make a  patch to LFE to address this ... I think there is some clever juggling we can do inside the `rebar.config` file that will essentially cause `make` to build the code without having to resort to manually ordering `.erl` and `.lfe` files in the LFE `rebar.config` file.
- If that doesn't work, we may simply have to resort to maintaining a list of `lfe_first_files` ... I guess all that would be needed in that list is `src/lfe_comp.erl` and the `.erl` files necessary to compile that one ...

@Dry-Jins Let us know how the `Makefile`` hack works for you ...

**Comment by rvirding** [comment] 2016-03-03 18:03
@oubiwann IIRC the problem is `rebar2` as it has a special internal hack which handles `.lfe` files which it does this by calling lfec on them. And at this time the `lfec` command hasn't been generated. As far as I know there is no way around. With `rebar3` this should be fixable in the rebar.config.

**Comment by oubiwann** [comment] 2016-03-04 00:04
@rvirding Hrm, I just did a grep of the rebar source code, and there's no reference to `lfec` -- only `lfe_comp:file`.

I'm going to try to reproduce this error (I've never actually run into it) and then see if we can come up with a good fix ... hopefully I'll have something we can look at tonight.

**Comment by rvirding** [comment] 2016-03-04 01:15
Yes, you're right, I had misinterpreted the error message. The problem seems to be how to get the `ebin` directory in the code from the beginning.

**Comment by oubiwann** [comment] 2016-03-04 01:17
Yup, that's what I've just run into -- it turns out `lfe_comp.beam` is actually already compiled ... so ordering isn't really the problem -- the problem is, as you've just said, it's not finding `lfe_comp` when it calls `code:which(lfe_comp)` ...

Still experimenting in a Docker instance  (on R16B03! and rebar 2.0.0!) ...

**Comment by oubiwann** [comment] 2016-03-04 01:55
Odd. Without setting `ERL_LIBS`, I get this:

```
# rebar compile -vvv
```

```
...
DEBUG: Worker exited cleanly
ERROR: 
*** MISSING LFE COMPILER ***
  You must do one of the following:
    a) Install LFE globally in your erl libs
    b) Add LFE as a dep for your project, eg:
       {lfe, "0.6.1",
        {git, "git://github.com/rvirding/lfe",
         {tag, "v0.6.1"}}}
```

Then, when I set `ERL_LIBS`, I get this:

```
# ERL_LIBS=./ rebar compile -vvv
```

```
...
DEBUG: Worker exited cleanly
ecp: #(cl ())
src/cl.lfe:522: illegal guard
DEBUG: Worker compilation failed: [{error,{error,failed}},
                                   {source,"src/cl.lfe"}]
```

Hrm, when starting up LFE and running in the REPL, I get the same thing:

```
# ./bin/lfe
```

``` cl
Erlang R16B03 (erts-5.10.4) [source] [64-bit] ...

LFE Shell V5.10.4 (abort with ^G)
> (c "./src/cl.lfe")
ecp: #(cl ())
./src/cl.lfe:522: illegal guard
error
```

**Comment by oubiwann** [comment] 2016-03-04 01:55
Well, crap -- it's the `is_map` guard.

**Comment by oubiwann** [comment] 2016-03-04 02:03
Okay, I submitted PR #190 to address this.

**Comment by oubiwann** [comment] 2016-03-04 02:19
@Dry-Jins: quick follow-up. We've got a fix in place -- the "work-around" I suggested to you earlier won't actually fix the problem you are seeing. If you want to compile right now, before the branch gets merged into `develop`, you can do _this_ work-around:
1. open up `src/cl.lfe`
2. go to line 606
3. change this:

`````` cl
  ((x) (when (is_map x))
   'map)
``

to this:

```cl
;  ((x) (when (is_map x))
;   'map)
``````

Then save & recompile, and you should be fine.

**Comment by yurrriq** [comment] 2016-03-04 03:21
Is there an `ifdef` equivalent in LFE?

**Comment by rvirding** [comment] 2016-03-04 16:44
No, there isn't, and I can't come up with a simple way of doing it. You can of course do tests inside a macro but in this case it would be difficult.

A hacky way of solving *this* problem would be to shift that clause last and just have maps as default of nothing else matches.

**Comment by yurrriq** [comment] 2016-03-04 18:03
~~What about putting the `is_map` in a `_` clause and checking `(if (is_function #'is_map/1) ...)`?~~

**Closed as completed** 2016-03-04 22:00 UTC
