### ISSUE TITLE
Store function docstrings

### ISSUE THREAD

**Issue by oubiwann** [lfe/lfe#87] opened 2014-09-01 17:47 UTC
In order to keep building the LFE REPL up as a first-class development tool, we're going to need so support displaying function docstrings (per issue #67). One of the first things that needs to be done for that, though, is to store the docstrings somewhere.

I'm not sure if there is some place to store metadata in compiled functions, but if that's not possible, we could add a module-level attribute "docstrings" with a proplist of `#(func-name func-docstring)` pairs ...

**Comment by yurrriq** [comment] 2015-07-13 04:00
This idea very much reminds me of Clojure's [`#'clojure.repl/doc`](https://github.com/clojure/clojure/blob/bdc752a7fefff5e63e0847836ae5e6d95f971c37/src/clj/clojure/repl.clj#L120-L129) and [`#'clojure.core/ns-map`](https://github.com/clojure/clojure/blob/bdc752a7fefff5e63e0847836ae5e6d95f971c37/src/clj/clojure/core.clj#L4017-L4022). It could be very awesome to implement something like [`IMeta`](https://github.com/clojure/clojure/blob/bdc752a7fefff5e63e0847836ae5e6d95f971c37/src/jvm/clojure/lang/IMeta.java#L15-L17) for LFE.

**Comment by yurrriq** [comment] 2016-04-04 06:56
This should probably be closed as a duplicate of #211.

**Comment by yurrriq** [comment] 2016-04-17 00:07
This functionality is merged into develop now.

**Closed as completed** 2016-11-07 11:15 UTC
Labels: documentation, feature
