### ISSUE TITLE
Error on exiting the shell

### ISSUE THREAD

**Issue by arpunk** [lfe/lfe#321] opened 2017-01-31 12:36 UTC
Currently in LFE when I issue `(q)` to quit the REPL I get the following error:

```
 λ lfe
Erlang/OTP 19 [erts-8.2.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

   ..-~.~_~---..
  (      \\     )    |   A Lisp-2+ on the Erlang VM
  |`-.._/_\\_.-':    |   Type (help) for usage info.
  |         g |_ \   |
  |        n    | |  |   Docs: http://docs.lfe.io/
  |       a    / /   |   Source: http://github.com/rvirding/lfe
   \     l    |_/    |
    \   r     /      |   LFE v1.3-dev (abort with ^G)
     `-E___.-'

lfe> (q)
ok
lfe> 2017-01-31 07:23:21 Error in process ~p with exit value:~n~p~n
	<0.53.0>
	{undef,[{io,format_error,[terminated],[]},{lfe_shell,'-list_ews/2-fun-0-',2,[{file,"src/lfe_shell.erl"},{line,437}]},{lists,foreach,2,[{file,"lists.erl"},{line,1338}]},{lfe_shell,server_loop,2,[{file,"src/lfe_shell.erl"},{line,117}]}]}
```

This does not happen within a rebar3 shell:

```
 λ rebar3 shell
===> Verifying dependencies...
===> Compiling lfe_example
 ~~> 	Finding .lfe files ...
Erlang/OTP 19 [erts-8.2.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:0] [hipe] [kernel-poll:false]

Eshell V8.2.1  (abort with ^G)
1> lfe_shell:start().
<0.138.0>
   ..-~.~_~---..
  (      \\     )    |   A Lisp-2+ on the Erlang VM
  |`-.._/_\\_.-':    |   Type (help) for usage info.
  |         g |_ \   |
  |        n    | |  |   Docs: http://docs.lfe.io/
  |       a    / /   |   Source: http://github.com/rvirding/lfe
   \     l    |_/    |
    \   r     /      |   LFE v1.3-dev (abort with ^G)
     `-E___.-'

lfe> (q)
ok 
lfe> %                                                                                                                                                               λ 
```

Current stable version (1.2.0) works fine within rebar3 shell too. I'm using Erlang 19.2.1 and LFE `develop` branch.

**Comment by yurrriq** [comment] 2017-02-02 06:23
I'm seeing the same behaviour on 1.2.1 (and `develop`) too.

**Comment by yurrriq** [comment] 2017-02-02 06:27
I just checked 1.0 and 0.9.2 (in an attempt to do a `git bisect`) and they both exhibit similar behaviour. FWIW I use `C-c C-c` or `C-g q` instead of `(q)` in practice.

**Comment by arpunk** [comment] 2017-02-03 13:31
@yurrriq Yea, I can live with `C-c C-c` but `(q)` is documented and used in Erlang shell aswell: `q().`

**Comment by arpunk** [comment] 2017-02-05 01:54
I also noticed that using latest `develop` I can no longer replicate the issue. These are the steps:

1) Create a rebar3 project and compile
2) Start a bare LFE repl within the project: `lfe`
3) Eval `(q)`

The REPL exists normally.

Since `develop` honors the `$REBAR_PROFILE` I wonder if having a rebar3 REPL plugin is worth the effort. Are there any pro/cons for having a rebar3 based REPL (as a plugin)?

**Comment by yurrriq** [comment] 2017-02-05 06:01
I think the only advantages would be that it's sort of standardized and offers hooks into the rebar3 flow. Beyond that, not really.

**Comment by rvirding** [comment] 2017-02-05 22:33
Yes, I tried to replicate the issue as well and couldn't get it to "work". I apparently managed to fix it "by mistake". 😄 I think the error came from trying to do output to a io device which had terminated so the error comes from the `io` module which doesn't contain a `format_error/1` function.

What would be the benefit of have a special rebar3 repl? Is there anything usefule we could add to the normal repl? I am only a very casual rebar3 user.

**Comment by arpunk** [comment] 2017-02-05 22:42
@rvirding rebar3 is going to be the de-facto package manager for Erlang. We honor the `$REBAR_PROFILE` which contains all the directories rebar3 creates when compiling a project.

Now it's possible to use rebar3 for project compilation and use the standard normal REPL to boot up the rebar3 compiled dependencies/apps without having to mess with special flags.

Since I don't know the rebar3 internals I'm unsure what other benefits are if using a rebar3 plugin instead of the normal REPL. Hot-code reloading of the whole project comes to mind though (i.e: `(recompile)`)

**Comment by rvirding** [comment] 2017-02-05 23:09
The question then becomes if we can plug in a special LFE repl in that case.

**Comment by oubiwann** [comment] 2017-02-06 00:10
Yeah, I think the main benefit of a rebar3-started REPL is that all the dependencies are made available.

One very distant benefit I have contemplated was using an LFE rebar3 REPL plugin to simulate a readline REPL history ... e.g., stored in dets, etc., and thus be available persistently, over the course of multiple REPL sessions.

**Comment by rvirding** [comment] 2017-02-06 16:14
The first issue is then how to get it to start an LFE repl instead of an Erlang repl, it already handles the paths.

**Comment by yurrriq** [comment] 2017-02-06 21:44
[`rebar_prv_alpaca_shell`](https://github.com/alpaca-lang/rebar_prv_alpaca/blob/shell/src/rebar_prv_alpaca_shell.erl) might provide some insight.

**Comment by rvirding** [comment] 2017-02-10 00:39
I *think* this was due to the REPL trying to read input and getting a `terminated` error from the module `io`. The `io` module doesn't have a `format_error` function which caused the error. I cannot reproduce it and don't rightly know why it has gone away.

I am closing this issue but we can reopen it if the error starts occurring again.

**Closed as completed by rvirding** 2017-02-10 00:39 UTC
