### ISSUE TITLE
Compile fail on Raspberry Pi Raspbian Wheezy

### ISSUE THREAD

**Issue by Bazmundi** [lfe/lfe#101] opened 2014-12-20 14:12 UTC
I get a compile fail on Raspberry Pi:

Compiling src/lfe_comp.erl failed:
src/lfe_comp.erl:30: can't find include lib "compiler/src/core_parse.hrl"
ERROR: compile failed while processing /home/pi/downloads/lfe: rebar_abort
make: **\* [compile] Error 1

This looks to me like either I have not set up environment correctly or the erlang/otp install is a binary only for Pi so erlang sources are not included.

In either event, has someone sorted getting lfe running on pi?

Cheers,
B

**Comment by Bazmundi** [comment] 2015-04-06 04:10
so, handed my dissertation in (finally) and now wife feels we are moving
house. This will likely not get looked at by me for another two months but
it is on my to do.

**Comment by arpunk** [comment] 2015-04-06 14:05
I think I have a Raspberry Pi somewhere around the office, once I find some time I can help you getting latest LFE built on it. Give me some days and I'll see what I can do.

**Comment by rvirding** [comment] 2015-04-06 15:22
The problem is that compiling LFE assumes that erlang has been installed with the sources. This is not always the default.

**Comment by oubiwann** [comment] 2020-10-14 17:11
Closing due to age.

**Closed as completed by oubiwann** 2020-10-14 17:11 UTC
Labels: bug, enhancement
