### ISSUE TITLE
Build problem on Ubuntu 14.04

### ISSUE THREAD

**Issue by sukubhatt** [lfe/lfe#182] opened 2016-01-25 05:47 UTC
I am facing issues building lfe on Ubuntu 14.04 - help needed! - any quick fixes?

Installed erlang with apt-get
Below is shown the erlang version installed.

sukumar@sukumar-Inspiron-5547:~/lfe$ erl -v
Erlang R16B03 (erts-5.10.4) [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]

Eshell V5.10.4  (abort with ^G)
1> 
^G

When I run make I get this
$ git clone https://github.com/rvirding/lfe.git
$ cd lfe
$ make 
.....
erlc -I include -o ebin  -W1 src/lfe_scan.erl
cc -o bin/lfeexec c_src/lfeexec.c
bin/lfec -I include -o ebin -pa ../lfe src/cl.lfe
/usr/bin/env: lfe: No such file or directory
make[1]: **\* [ebin/cl.beam] Error 127
rm src/lfe_scan.erl
make[1]: Leaving directory `/home/sukumar/lfe'
make: **\* [compile] Error 2

Clearly bin/lfec is trying to run lfe but lfe is not installed - so I do "make install" which installs a softlink to bin/lfe in /usr/bin

Now, I get this ..
sukumar@sukumar-Inspiron-5547:~/lfe$ make
if which rebar.cmd > /dev/null; \
    then ERL_LIBS=.:$ERL_LIBS rebar.cmd compile; \
    elif which rebar > /dev/null; \
    then ERL_LIBS=.:$ERL_LIBS rebar compile; \
    else \
    make  erlc-lfec; \
    fi
make[1]: Entering directory `/home/sukumar/lfe'
bin/lfec -I include -o ebin -pa ../lfe src/cl.lfe
src/cl.lfe:539: illegal guard
make[1]: *** [ebin/cl.beam] Error 1
make[1]: Leaving directory`/home/sukumar/lfe'
make: **\* [compile] Error 2

**Comment by yurrriq** [comment] 2016-01-25 06:39
I haven't built LFE recently, so I can't comment explicitly on the guard issue, but that's a fairly old version of Erlang. If possible (though not required, to the best of my knowledge) I'd suggest at least 17.5.

Package managers are generally pretty far behind when it comes to Erlang. I'd recommend using something like kerl to manage installations.

**Comment by yurrriq** [comment] 2016-01-25 06:41
~~After a quick glance at `cl:type-of/1` I don't see any illegal guards either..~~

**Comment by rvirding** [comment] 2016-01-25 15:27
First the simple problem: not being able to run lfec can be fixed by the following modification to Makefile:

```
-LFEC = bin/lfec
+LFEC = bin/lfe bin/lfec
```

I will include this in future commits. The problem with rebar2 is worse, at least I cannot fix it, as I don't how to tell rebars2 how to compile lfe files. Calling lfec seems to be hard-wired. If anyone knows of a solution please tell me.

What about rebar3? Can we control it?

**Comment by rvirding** [comment] 2016-01-25 15:40
The other problem is worse. The cause of the problem is that you are running on R16B which doesn't have maps and my handling of some of the map bifs is not good. In this case is_map/1 is not recognised as a bif so you get the illegal guard error. I don't really know what to do here. For all the core forms I generate compile time errors when they are used, here it happens automatically in the guard.

The question is what should I do? What is best? For is_map I could just return return false but what about the errors. I suppose for user code it is alright to fail but for not for the system itself.

**Comment by oubiwann** [comment] 2016-01-25 15:57
Hrm, rebar2 automatically compiles `*.lfe` files if it detects them in a project.  I don't expect that would be causing a problem here ...

(By default, rebar3 does not, but we have created plugins for that -- but, yes, we do control it :-))

@rvirding ... maybe it would be worth implementing a dynamically-supplied function for  v < 17? Something that just returns `#(error "Maps unsupported in the current version of Erlang being used.")`?

**Comment by rvirding** [comment] 2016-01-25 16:13
The main problem with rebar2 compiling .lfe files is that it does by trying to call lfec which doesn't work when compiling the .lfe files LFE itself as lfec hasn't been installed yet.

With rebar3 I think the best solution would be to first try lfec and if it doesn't exist assume you are in the LFE directory and try 'bin/lfe bin/lfec' and if that doesn't exist and the use hasn't defined anything else generate an error.

**Comment by oubiwann** [comment] 2016-01-25 16:31
Ohhhhhh, I see. Yeah :-(

**Comment by sukubhatt** [comment] 2016-01-26 16:27
btw, I did not install rebar.

Actually I had earlier installed the latest (18.2?) from erlang solutions and followed the gitbook exactly including installing rebar - but had problems - I think the compile got stuck on lfe_scan.xrl - hence I decided to go with the Ubuntu official version without rebar and posted the results as earlier.

I will try Erlang 17.5 and 18.1 using kerl and let you know the results soon.

Thanks for your help!
- Sukumar

--------- Original Message --------- Subject: Re: [lfe] Build problem on Ubuntu 14.04 (#182)

**Comment by sukubhatt** [comment] 2016-01-27 09:23
Builds (and works) with both 17.5 and 18.1 without any hitch. Again - built without rebar.

Thanks.
-Sukumar

**Comment by sukubhatt** [comment] 2016-02-05 10:14
Some minor feedback.

I have now installed on Ubuntu 14.04, Erlang 18.1 at /usr/local/ and am not using kerl as before.
I have done a re-make of lfe.

Starting 'lfe' from a terminal shell (bash) works.
Also doing 'run-lfe' in emacs works.

However when I try to run 'lfe' in an emacs shell it lands me in an Erlang shell instead of the LFE shell - can't quite figure out why.

I also tried (as given in the LFE User Guide)
$ erl -user lfe_init -pa /home/sukumar/lfe/ebin

This again lands up in the Erlang shell when run in the emacs shell but works correctly when run in a terminal shell (bash).

**Comment by yurrriq** [comment] 2016-02-05 17:42
@sukubhatt, does `M-x inferior-lfe` work for you?

**Comment by rvirding** [comment] 2016-02-06 14:00
In this case the problem is with the Erlang libraries. It all depends on the properties of the terminal/window in each the LFE repl is run. So when you start erlang and give it another shell to use, which is what we do, then it will only use that shell iff the terminal/window is in character mode. If it is in line mode then it automatically reverts the erlang shell. Unfortunately this is hard wired.

A simple work around is to call `lfe_shell:server().` from the erlang shell. Not good I know but it works.

One solution I am toying with is to have a private LFE version of the erlang library which does this which doesn't do this. Another hacky work-around similar to what is needed to get dialyzer to work with LFE code.

**Comment by sukubhatt** [comment] 2016-02-06 17:04
Yes - M-x inferior-lfe works - as I said earlier M-x run-lfe works (and run-lfe calls inferior-lfe so that would work) - but I also explicitly did M-x inferior-lfe since you asked and that worked.

Thanks,
Sukumar

--------- Original Message --------- Subject: Re: [lfe] Build problem on Ubuntu 14.04 (#182)

**Comment by sukubhatt** [comment] 2016-02-06 17:15
Robert,

I already did that - lfe_shell:server() - before i wrote that mail - and that works.

But since M-x run-lfe is working, we don't really need that work-around - and we don't need to run lfe in the emacs shell either.

My intent in posting that was in the hope that maybe some small configuration change in the emacs shell could iron out the problem - but if it requires the kind of change you wrote about, then my recommendation would be to leave things as it is.

As the Chinese saying goes - "the best is the enemy of the good" - so as long as things are working well enough we need not waste our time nit-picking and making things perfect since there is no limit to that.

Thanks - LFE is great and I hope to do many interesting things with it.

You may close the issue now if you wish (or do I need to do that since I opened it? - in that case just let me know)

Thanks again,
Sukumar

--------- Original Message --------- Subject: Re: [lfe] Build problem on Ubuntu 14.04 (#182)

**Comment by rvirding** [comment] 2016-03-10 23:20
The original error when compiling cl.lfe was fixed in cdbd0c969b64711f8bd57274444636ca76fe4933

**Comment by rvirding** [comment] 2016-03-10 23:22
The original error when compiling cl.lfe was fixed in cdbd0c969b64711f8bd57274444636ca76fe4933

**Closed as completed by rvirding** 2016-03-10 23:22 UTC
